import { ProgressionTemplate } from '../types'

export const aMinorBlues: ProgressionTemplate = {
  bars: {
    'pop-song-1-qIuAuo4aDQTTyIsA53Z_W': {
      id: 'pop-song-1-qIuAuo4aDQTTyIsA53Z_W',
      chords: ['pop-song-1-Vc1EG-eJ3wij-9JW7PjxG'],
    },
    'pop-song-1-wwsQ3tv9MzT0nLUCBGgR0': {
      id: 'pop-song-1-wwsQ3tv9MzT0nLUCBGgR0',
      chords: ['pop-song-1-WrOV-fgVqkTHpt9Iog2yl'],
    },
    'pop-song-1-3Jwlu0zFQmG2ENVrpl8qd': {
      id: 'pop-song-1-3Jwlu0zFQmG2ENVrpl8qd',
      chords: ['pop-song-1-HI-jhF8fLeMhrRXKVki7L'],
    },
    'pop-song-1-W-SSNMqoQD1LTd5Jn-baB': {
      id: 'pop-song-1-W-SSNMqoQD1LTd5Jn-baB',
      chords: ['pop-song-1-52oysKexbC7_5iF5AxojP'],
    },
    'pop-song-1-bsd-4rT_TXIrmqCnYm6Ak': {
      id: 'pop-song-1-bsd-4rT_TXIrmqCnYm6Ak',
      chords: ['pop-song-1-tx3sm7AbC2hNS1MZWtUC5'],
    },
    'pop-song-1-FcnYwOhKE0GNX5YDkuEXN': {
      id: 'pop-song-1-FcnYwOhKE0GNX5YDkuEXN',
      chords: ['pop-song-1-ZxCv93wUscP--vBZHPjEV'],
    },
    'pop-song-1-iRHsHGV2npfhzr68yep5a': {
      id: 'pop-song-1-iRHsHGV2npfhzr68yep5a',
      chords: ['pop-song-1-FO53MOhldkWVcN4jlNqV4'],
    },
    'pop-song-1-4LBUq6dLnSlkMgDCxS4aA': {
      id: 'pop-song-1-4LBUq6dLnSlkMgDCxS4aA',
      chords: ['pop-song-1-ZgtwVfKbDlj8gM3kYAX34'],
    },
    'pop-song-1-oxUyFReSLrUIEqLC15u4C': {
      id: 'pop-song-1-oxUyFReSLrUIEqLC15u4C',
      chords: ['pop-song-1-QPAU8BhhPNSJvHkScyxn7'],
    },
    'pop-song-1-OF9c_o_3N5Wi0Oclinw9Z': {
      id: 'pop-song-1-OF9c_o_3N5Wi0Oclinw9Z',
      chords: ['pop-song-1-za-8KKoFlXRM45JsXfF8z'],
    },
    'pop-song-1-rLdJcPNDGlny8bxhGI5Qa': {
      id: 'pop-song-1-rLdJcPNDGlny8bxhGI5Qa',
      chords: ['pop-song-1-XmVx_9gon8phtLiCNRKeM'],
    },
    'pop-song-1-zuixJBYrkGXz7hI1E6Ph2': {
      id: 'pop-song-1-zuixJBYrkGXz7hI1E6Ph2',
      chords: ['pop-song-1-kyDxtERtc8--7QKK-NyEt'],
    },
    'pop-song-1-B6aQy2tGdC78W-sHc815m': {
      id: 'pop-song-1-B6aQy2tGdC78W-sHc815m',
      chords: ['pop-song-1-bCqghYtFzSRFLnLdVHwUX'],
    },
    'pop-song-1-ScBDcKxqhn0jbFT-invVn': {
      id: 'pop-song-1-ScBDcKxqhn0jbFT-invVn',
      chords: ['pop-song-1-tboQuB0IlPzZ5uWA0x1CE'],
    },
    'pop-song-1-nz17rtg7GMuCuaKgEsW4y': {
      id: 'pop-song-1-nz17rtg7GMuCuaKgEsW4y',
      chords: ['pop-song-1-K1jOwYelDFOQN5WS0lNRq'],
    },
    'pop-song-1-NYyMzVmSC7fXGyKNq9TTX': {
      id: 'pop-song-1-NYyMzVmSC7fXGyKNq9TTX',
      chords: ['pop-song-1-av4OOISO7XWhgnOkwVV3V'],
    },
    'pop-song-1-nXqM5TPgJz6VFBul5q2Wx': {
      id: 'pop-song-1-nXqM5TPgJz6VFBul5q2Wx',
      chords: ['pop-song-1-jGgPEtYXrQnqTYSkqVJrL'],
    },
    'pop-song-1-Pg1wYW84STb9j_xQXrL6-': {
      id: 'pop-song-1-Pg1wYW84STb9j_xQXrL6-',
      chords: ['pop-song-1-mywDqyxlDOK3B7Ka4ZIpo'],
    },
    'pop-song-1-bQm5vDpHpLWViR4ztp9EK': {
      id: 'pop-song-1-bQm5vDpHpLWViR4ztp9EK',
      chords: ['pop-song-1-zhK-IGeCp24sdfvMG70of'],
    },
    'pop-song-1-2-PZAKLTZgk-dzL-Ez3td': {
      id: 'pop-song-1-2-PZAKLTZgk-dzL-Ez3td',
      chords: ['pop-song-1-PC8rXli91ouFRXH3XldO1'],
    },
    'pop-song-1-TG9zZ-0gXJcXTwvSFp26e': {
      id: 'pop-song-1-TG9zZ-0gXJcXTwvSFp26e',
      chords: ['pop-song-1-gIYBkBOlcdm7ZAmS_BG96'],
    },
    'pop-song-1-u4XgX5NQBqx2MAe00CdSL': {
      id: 'pop-song-1-u4XgX5NQBqx2MAe00CdSL',
      chords: ['pop-song-1-NxDkVyx5AdBVz0CuicKZ4'],
    },
    'pop-song-1-ZJlFJ2PNiwZ4GY7BGLwuw': {
      id: 'pop-song-1-ZJlFJ2PNiwZ4GY7BGLwuw',
      chords: ['pop-song-1-ndyDpwx5k0OqWbd9J1oEA'],
    },
    'pop-song-1-2InaOI02hK6I90wh8iw0_': {
      id: 'pop-song-1-2InaOI02hK6I90wh8iw0_',
      chords: ['pop-song-1-DG3BGPpSacy0iN6YfR4zZ'],
    },
    'pop-song-1-7gbzo4eAfbTHT47v4THHk': {
      id: 'pop-song-1-7gbzo4eAfbTHT47v4THHk',
      chords: ['pop-song-1-dY9HY0rgj7sk_udwQIDUI'],
    },
    'pop-song-1-ISKyguTKV6Ly5Va_oaIad': {
      id: 'pop-song-1-ISKyguTKV6Ly5Va_oaIad',
      chords: ['pop-song-1-Un5ZSxXktuR_PVKEtsfzd'],
    },
    'pop-song-1-Gr0yPOo0Fuz-wGQIRsDUs': {
      id: 'pop-song-1-Gr0yPOo0Fuz-wGQIRsDUs',
      chords: [
        'pop-song-1-yjCwalMCOa3g2ESTjzod-',
        'pop-song-1-F7xXlZy_xDJ7Iz4Soxykc',
      ],
    },
    'pop-song-1-XqMQl2h2jUG0tRd-JeQDF': {
      id: 'pop-song-1-XqMQl2h2jUG0tRd-JeQDF',
      chords: [
        'pop-song-1-6rUDc4PL7OUENHE0885vS',
        'pop-song-1-ZAob4SrtAo1ETURvb92aU',
      ],
    },
    'pop-song-1-lpBMzQ_hrl_pT1wWF-fwo': {
      id: 'pop-song-1-lpBMzQ_hrl_pT1wWF-fwo',
      chords: ['pop-song-1-TOJTLviVSapIo3xOiQhE2'],
    },
    'pop-song-1-_aikcR2m2czBqQGFbAUPF': {
      id: 'pop-song-1-_aikcR2m2czBqQGFbAUPF',
      chords: ['pop-song-1-htwvbqfLNMfHdV5IwxnQT'],
    },
    'pop-song-1-D8vjsDpoQJyW-MjFbueHD': {
      id: 'pop-song-1-D8vjsDpoQJyW-MjFbueHD',
      chords: ['pop-song-1-NtLDHPLQbBDta70vWrV6Y'],
    },
    'pop-song-1-Qc31CQqJYmSOpzd99oErs': {
      id: 'pop-song-1-Qc31CQqJYmSOpzd99oErs',
      chords: ['pop-song-1-vqrKpw3N4TNtqEhszM08H'],
    },
    I6eeyXIMunCx8sf7vN9ns: {
      id: 'I6eeyXIMunCx8sf7vN9ns',
      chords: ['Z5vsASB1VftNHM619jwoR'],
    },
    'Y8prv9H-PgYQ3_l_YmDNu': {
      id: 'Y8prv9H-PgYQ3_l_YmDNu',
      chords: ['qT_uLfkOeEK5jlWjhljIH'],
    },
    CJVoKXLBbEMDt0Q9mGoYw: {
      id: 'CJVoKXLBbEMDt0Q9mGoYw',
      chords: ['CNJk27V9yL9p4Fstrkz0A'],
    },
    oZ7fH8GzFA55U6V4Rt_RP: {
      id: 'oZ7fH8GzFA55U6V4Rt_RP',
      chords: ['vAkCIfINp9vJcmqdCqltG'],
    },
    '2wIxsAhovD21C0CcV9M6I': {
      id: '2wIxsAhovD21C0CcV9M6I',
      chords: ['zjBUtk7s9FuMfLdPc9Wsq'],
    },
    'KVXMSLmk16hD-AWT3IHPa': {
      id: 'KVXMSLmk16hD-AWT3IHPa',
      chords: ['nEPJKVx0rxrFXnYUW7nTf'],
    },
    aIANv9TSnW3sop0mYmnMJ: {
      id: 'aIANv9TSnW3sop0mYmnMJ',
      chords: ['_OxY6GxGEbvuDIenQpuNk'],
    },
    kInEsg3rC489M9E6MHRZW: {
      id: 'kInEsg3rC489M9E6MHRZW',
      chords: ['wjGaAPDgunpWO6Qar0B7W'],
    },
    fiKKVm4pPowxlsFwaa2yL: {
      id: 'fiKKVm4pPowxlsFwaa2yL',
      chords: ['jle98VDKu2SuLZZlUAul1'],
    },
    '7D-PwW_OdU6X_ZkifaM4E': {
      id: '7D-PwW_OdU6X_ZkifaM4E',
      chords: ['I4IgvFRWj65GcAjy70xVy'],
    },
    '8pW5mBtRvne7DqZeNKg51': {
      id: '8pW5mBtRvne7DqZeNKg51',
      chords: ['zJAxqcSnwl7XLrnF1PhlO'],
    },
    '7MHRGE0hSM8KPNdL5ogZT': {
      id: '7MHRGE0hSM8KPNdL5ogZT',
      chords: ['glly4WY89nbNVxUiZS1L5'],
    },
    'lh492YRPr1_3-X1W_mJkE': {
      id: 'lh492YRPr1_3-X1W_mJkE',
      chords: ['yDkF9XpcbKi17othzHAtU'],
    },
    'dy-Pe9Kor5sYut2YqZZnq': {
      id: 'dy-Pe9Kor5sYut2YqZZnq',
      chords: ['5cr_VRnxxrUh2fp7JtI0q'],
    },
    AVobrClqosfmFICzH4XJb: {
      id: 'AVobrClqosfmFICzH4XJb',
      chords: ['ejSvbgqz4n3cm9stavm9D'],
    },
    'imT9nu-fnX012riKPlOzU': {
      id: 'imT9nu-fnX012riKPlOzU',
      chords: ['8ASsz6KpPWRow-Np80jlw'],
    },
    FsPyvn908XbeiMHZ2dwYW: {
      id: 'FsPyvn908XbeiMHZ2dwYW',
      chords: ['UOpwzhbGvIRBlupONeZez'],
    },
    '1JuD0Shgvmcei9a5awVlU': {
      id: '1JuD0Shgvmcei9a5awVlU',
      chords: ['ks_fADjB0VROjEpIGI9SD'],
    },
    'uAJHw6OHhl8KUl-756EEZ': {
      id: 'uAJHw6OHhl8KUl-756EEZ',
      chords: ['ZjWOywKMoESBn7rFzBu68'],
    },
    egbLaSaQrp9pz92v7F3yb: {
      id: 'egbLaSaQrp9pz92v7F3yb',
      chords: ['nme6br7Zr_3CwoXnK6yMw'],
    },
    NpklWphie8nVyO23_Y6sc: {
      id: 'NpklWphie8nVyO23_Y6sc',
      chords: ['KkGbGqsjZuwVvwhWrzsF1'],
    },
    lmqyAakOy2FYpPJ5iUtll: {
      id: 'lmqyAakOy2FYpPJ5iUtll',
      chords: ['W0oh7HnRNCkAUU6ALNW3w'],
    },
    zwcSoX_FKO0RNIot7PWCG: {
      id: 'zwcSoX_FKO0RNIot7PWCG',
      chords: ['6FBISXQ0BcPyuvWUnPQxU'],
    },
    'yluFxCrXTEm-YpQDi_qX3': {
      id: 'yluFxCrXTEm-YpQDi_qX3',
      chords: ['-xJHytcdXXLqYFFxXosOg'],
    },
  },
  chords: {
    'pop-song-1-Vc1EG-eJ3wij-9JW7PjxG': {
      id: 'pop-song-1-Vc1EG-eJ3wij-9JW7PjxG',
      name: 'C',
      type: 'MINOR-SEVENTH',
      root: 'C2',
      transitionId: 'S?;T?;C,R->C,T,U->C,F,U->N,R+1;',
    },
    'pop-song-1-WrOV-fgVqkTHpt9Iog2yl': {
      id: 'pop-song-1-WrOV-fgVqkTHpt9Iog2yl',
      name: 'F',
      type: 'DOMINANT-SEVENTH',
      root: 'F1',
      transitionId: 'S?;T?;C,R->C,T,U->C,F,U->N,R-1;',
    },
    'pop-song-1-HI-jhF8fLeMhrRXKVki7L': {
      id: 'pop-song-1-HI-jhF8fLeMhrRXKVki7L',
      name: 'Bb',
      type: 'MAJOR-SEVENTH',
      root: 'Bb1',
      transitionId: 'S?;T?;C,R->C,T,U->C,F,U->N,R+1;',
    },
    'pop-song-1-52oysKexbC7_5iF5AxojP': {
      id: 'pop-song-1-52oysKexbC7_5iF5AxojP',
      name: 'Eb',
      type: 'MAJOR-SEVENTH',
      root: 'Eb2',
      transitionId: 'S?;T?;C,R->C,T,D->C,F,U->N,R+1;',
    },
    'pop-song-1-tx3sm7AbC2hNS1MZWtUC5': {
      id: 'pop-song-1-tx3sm7AbC2hNS1MZWtUC5',
      name: 'A',
      type: 'DIMINISHED',
      root: 'A1',
      transitionId: 'S?;T?;C,R->C,T,U->C,F,U->N,R-1;',
    },
    'pop-song-1-ZxCv93wUscP--vBZHPjEV': {
      id: 'pop-song-1-ZxCv93wUscP--vBZHPjEV',
      name: 'D',
      type: 'DOMINANT-SEVENTH',
      root: 'D2',
      transitionId: 'S?;T?;C,R->C,T,D->C,F,U->N,R-1;',
    },
    'pop-song-1-FO53MOhldkWVcN4jlNqV4': {
      id: 'pop-song-1-FO53MOhldkWVcN4jlNqV4',
      name: 'G',
      type: 'MINOR-SEVENTH',
      root: 'G1',
      transitionId: 'S?;T?;C,R->C,T,U->C,F,U->N,R-1;',
    },
    'pop-song-1-ZgtwVfKbDlj8gM3kYAX34': {
      id: 'pop-song-1-ZgtwVfKbDlj8gM3kYAX34',
      name: 'G',
      type: 'MINOR-SEVENTH',
      root: 'G1',
      transitionId: 'S?;T?;C,R->C,T,U->C,F,U->N,R-1;',
    },
    'pop-song-1-QPAU8BhhPNSJvHkScyxn7': {
      id: 'pop-song-1-QPAU8BhhPNSJvHkScyxn7',
      name: 'C',
      type: 'MINOR-SEVENTH',
      root: 'C2',
      transitionId: 'S?;T?;C,R->C,T,U->C,F,U->N,R-1;',
    },
    'pop-song-1-za-8KKoFlXRM45JsXfF8z': {
      id: 'pop-song-1-za-8KKoFlXRM45JsXfF8z',
      name: 'F',
      type: 'DOMINANT-SEVENTH',
      root: 'F1',
      transitionId: 'S?;T?;C,R->C,T,U->C,F,U->N,R-1;',
    },
    'pop-song-1-XmVx_9gon8phtLiCNRKeM': {
      id: 'pop-song-1-XmVx_9gon8phtLiCNRKeM',
      name: 'Bb',
      type: 'MAJOR-SEVENTH',
      root: 'Bb1',
      transitionId: 'S?;T?;C,R->C,T,U->C,F,D->N,R+1;',
    },
    'pop-song-1-kyDxtERtc8--7QKK-NyEt': {
      id: 'pop-song-1-kyDxtERtc8--7QKK-NyEt',
      name: 'Eb',
      type: 'MAJOR-SEVENTH',
      root: 'Eb2',
      transitionId: 'S?;T?;C,R->C,T,U->C,F,U->N,R-1;',
    },
    'pop-song-1-bCqghYtFzSRFLnLdVHwUX': {
      id: 'pop-song-1-bCqghYtFzSRFLnLdVHwUX',
      name: 'A',
      type: 'DIMINISHED',
      root: 'A1',
      transitionId: 'S?;T?;C,R->C,T,U->C,F,U->N,R+1;',
    },
    'pop-song-1-tboQuB0IlPzZ5uWA0x1CE': {
      id: 'pop-song-1-tboQuB0IlPzZ5uWA0x1CE',
      name: 'D',
      type: 'DOMINANT-SEVENTH',
      root: 'D2',
      transitionId: 'S?;T?;C,R->C,T,D->C,F,U->N,R-1;',
    },
    'pop-song-1-K1jOwYelDFOQN5WS0lNRq': {
      id: 'pop-song-1-K1jOwYelDFOQN5WS0lNRq',
      name: 'G',
      type: 'MINOR-SEVENTH',
      root: 'G1',
      transitionId: 'S?;T?;C,R->C,T,U->C,F,U->N,R+1;',
    },
    'pop-song-1-av4OOISO7XWhgnOkwVV3V': {
      id: 'pop-song-1-av4OOISO7XWhgnOkwVV3V',
      name: 'G',
      type: 'MINOR-SEVENTH',
      root: 'G1',
      transitionId: 'S?;T?;C,R->C,T,U->C,F,U->N,R-1;',
    },
    'pop-song-1-jGgPEtYXrQnqTYSkqVJrL': {
      id: 'pop-song-1-jGgPEtYXrQnqTYSkqVJrL',
      name: 'A',
      type: 'DIMINISHED',
      root: 'A1',
      transitionId: 'S?;T?;C,R->C,T,U->C,F,U->N,R+1;',
    },
    'pop-song-1-mywDqyxlDOK3B7Ka4ZIpo': {
      id: 'pop-song-1-mywDqyxlDOK3B7Ka4ZIpo',
      name: 'D',
      type: 'DOMINANT-SEVENTH',
      root: 'D2',
      transitionId: 'S?;T?;C,R->C,T,U->C,F,D->N,R-1;',
    },
    'pop-song-1-zhK-IGeCp24sdfvMG70of': {
      id: 'pop-song-1-zhK-IGeCp24sdfvMG70of',
      name: 'G',
      type: 'MINOR-SEVENTH',
      root: 'G1',
      transitionId: 'S?;T?;C,R->C,T,U->C,F,U->N,R-1;',
    },
    'pop-song-1-PC8rXli91ouFRXH3XldO1': {
      id: 'pop-song-1-PC8rXli91ouFRXH3XldO1',
      name: 'G',
      type: 'MINOR-SEVENTH',
      root: 'G1',
      transitionId: 'S?;T?;C,R->C,T,U->C,F,U->N,R+1;',
    },
    'pop-song-1-gIYBkBOlcdm7ZAmS_BG96': {
      id: 'pop-song-1-gIYBkBOlcdm7ZAmS_BG96',
      name: 'C',
      type: 'MINOR-SEVENTH',
      root: 'C2',
      transitionId: 'S?;T?;C,R->C,T,U->C,F,U->N,R-1;',
    },
    'pop-song-1-NxDkVyx5AdBVz0CuicKZ4': {
      id: 'pop-song-1-NxDkVyx5AdBVz0CuicKZ4',
      name: 'F',
      type: 'DOMINANT-SEVENTH',
      root: 'F1',
      transitionId: 'S?;T?;C,R->C,T,U->C,F,U->N,R-1;',
    },
    'pop-song-1-ndyDpwx5k0OqWbd9J1oEA': {
      id: 'pop-song-1-ndyDpwx5k0OqWbd9J1oEA',
      name: 'Bb',
      type: 'MAJOR-SEVENTH',
      root: 'Bb1',
      transitionId: 'S?;T?;C,R->C,T,U->C,F,U->N,R+1;',
    },
    'pop-song-1-DG3BGPpSacy0iN6YfR4zZ': {
      id: 'pop-song-1-DG3BGPpSacy0iN6YfR4zZ',
      name: 'Bb',
      type: 'MAJOR-SEVENTH',
      root: 'Bb1',
      transitionId: 'S?;T?;C,R->C,T,U->C,F,D->N,R-1;',
    },
    'pop-song-1-dY9HY0rgj7sk_udwQIDUI': {
      id: 'pop-song-1-dY9HY0rgj7sk_udwQIDUI',
      name: 'A',
      type: 'DIMINISHED',
      root: 'A1',
      tags: [],
      transitionId: 'S?;T?;C,R->C,T,U->C,F,U->N,R+1;',
    },
    'pop-song-1-Un5ZSxXktuR_PVKEtsfzd': {
      id: 'pop-song-1-Un5ZSxXktuR_PVKEtsfzd',
      name: 'D',
      type: 'DOMINANT-SEVENTH',
      root: 'D2',
      tags: [],
      transitionId: 'S?;T?;C,R->C,T,D->C,F,D->N,R+1;',
    },
    'pop-song-1-yjCwalMCOa3g2ESTjzod-': {
      id: 'pop-song-1-yjCwalMCOa3g2ESTjzod-',
      name: 'G',
      type: 'MINOR-SEVENTH',
      root: 'G1',
      transitionId: 'S?;T?;C,R->C,T,U->C,F,U->N,R+1;',
    },
    'pop-song-1-F7xXlZy_xDJ7Iz4Soxykc': {
      id: 'pop-song-1-F7xXlZy_xDJ7Iz4Soxykc',
      name: 'Gb',
      type: 'DOMINANT-SEVENTH',
      root: 'Gb1',
      transitionId: 'S?;T?;C,R->C,T,U->C,F,U->N,R-1;',
    },
    'pop-song-1-6rUDc4PL7OUENHE0885vS': {
      id: 'pop-song-1-6rUDc4PL7OUENHE0885vS',
      name: 'F',
      type: 'MINOR-SEVENTH',
      root: 'F1',
      transitionId: 'S?;T?;C,R->C,T,U->C,F,U->N,R+1;',
    },
    'pop-song-1-ZAob4SrtAo1ETURvb92aU': {
      id: 'pop-song-1-ZAob4SrtAo1ETURvb92aU',
      name: 'E',
      type: 'DOMINANT-SEVENTH',
      root: 'E1',
      transitionId: 'S?;T?;C,R->C,T,U->C,F,U->N,R-1;',
    },
    'pop-song-1-TOJTLviVSapIo3xOiQhE2': {
      id: 'pop-song-1-TOJTLviVSapIo3xOiQhE2',
      name: 'Eb',
      type: 'MAJOR-SEVENTH',
      root: 'Eb2',
      transitionId: 'S?;T?;C,R->C,T,D->C,F,U->N,R+1;',
    },
    'pop-song-1-htwvbqfLNMfHdV5IwxnQT': {
      id: 'pop-song-1-htwvbqfLNMfHdV5IwxnQT',
      name: 'D',
      type: 'DOMINANT-SEVENTH',
      root: 'D2',
      transitionId: 'S?;T?;C,R->C,T,D->C,F,U->N,R-1;',
    },
    'pop-song-1-NtLDHPLQbBDta70vWrV6Y': {
      id: 'pop-song-1-NtLDHPLQbBDta70vWrV6Y',
      name: 'G',
      type: 'MINOR-SEVENTH',
      root: 'G1',
      transitionId: 'S?;T?;C,R->C,T,U->C,F,U->N,R+1;',
    },
    'pop-song-1-vqrKpw3N4TNtqEhszM08H': {
      id: 'pop-song-1-vqrKpw3N4TNtqEhszM08H',
      name: 'G',
      type: 'MINOR-SEVENTH',
      root: 'G1',
    },
    Z5vsASB1VftNHM619jwoR: {
      id: 'Z5vsASB1VftNHM619jwoR',
      name: 'A',
      type: 'MINOR',
      root: 'A1',
    },
    qT_uLfkOeEK5jlWjhljIH: {
      id: 'qT_uLfkOeEK5jlWjhljIH',
      name: 'A',
      type: 'MINOR',
      root: 'A1',
    },
    CNJk27V9yL9p4Fstrkz0A: {
      id: 'CNJk27V9yL9p4Fstrkz0A',
      name: 'A',
      type: 'MINOR',
      root: 'A1',
    },
    vAkCIfINp9vJcmqdCqltG: {
      id: 'vAkCIfINp9vJcmqdCqltG',
      name: 'A',
      type: 'MINOR',
      root: 'A1',
    },
    zjBUtk7s9FuMfLdPc9Wsq: {
      id: 'zjBUtk7s9FuMfLdPc9Wsq',
      name: 'D',
      type: 'MINOR',
      root: 'D2',
    },
    nEPJKVx0rxrFXnYUW7nTf: {
      id: 'nEPJKVx0rxrFXnYUW7nTf',
      name: 'D',
      type: 'MINOR',
      root: 'D2',
    },
    _OxY6GxGEbvuDIenQpuNk: {
      id: '_OxY6GxGEbvuDIenQpuNk',
      name: 'A',
      type: 'MINOR',
      root: 'A1',
    },
    wjGaAPDgunpWO6Qar0B7W: {
      id: 'wjGaAPDgunpWO6Qar0B7W',
      name: 'A',
      type: 'MINOR',
      root: 'A1',
    },
    jle98VDKu2SuLZZlUAul1: {
      id: 'jle98VDKu2SuLZZlUAul1',
      name: 'E',
      type: 'MINOR',
      root: 'E1',
    },
    I4IgvFRWj65GcAjy70xVy: {
      id: 'I4IgvFRWj65GcAjy70xVy',
      name: 'D',
      type: 'MINOR',
      root: 'D2',
    },
    zJAxqcSnwl7XLrnF1PhlO: {
      id: 'zJAxqcSnwl7XLrnF1PhlO',
      name: 'A',
      type: 'MINOR',
      root: 'A1',
    },
    glly4WY89nbNVxUiZS1L5: {
      id: 'glly4WY89nbNVxUiZS1L5',
      name: 'E',
      type: 'DOMINANT-SEVENTH',
      root: 'E1',
    },
    '8ASsz6KpPWRow-Np80jlw': {
      id: '8ASsz6KpPWRow-Np80jlw',
      name: 'A',
      type: 'MINOR',
      root: 'A1',
    },
    UOpwzhbGvIRBlupONeZez: {
      id: 'UOpwzhbGvIRBlupONeZez',
      name: 'D',
      type: 'MINOR',
      root: 'D2',
    },
    ks_fADjB0VROjEpIGI9SD: {
      id: 'ks_fADjB0VROjEpIGI9SD',
      name: 'D',
      type: 'MINOR',
      root: 'D2',
    },
    ZjWOywKMoESBn7rFzBu68: {
      id: 'ZjWOywKMoESBn7rFzBu68',
      name: 'A',
      type: 'MINOR',
      root: 'A1',
    },
    nme6br7Zr_3CwoXnK6yMw: {
      id: 'nme6br7Zr_3CwoXnK6yMw',
      name: 'A',
      type: 'MINOR',
      root: 'A1',
    },
    KkGbGqsjZuwVvwhWrzsF1: {
      id: 'KkGbGqsjZuwVvwhWrzsF1',
      name: 'E',
      type: 'MINOR',
      root: 'E1',
    },
    W0oh7HnRNCkAUU6ALNW3w: {
      id: 'W0oh7HnRNCkAUU6ALNW3w',
      name: 'D',
      type: 'MINOR',
      root: 'D2',
    },
    '-xJHytcdXXLqYFFxXosOg': {
      id: '-xJHytcdXXLqYFFxXosOg',
      name: 'E',
      type: 'DOMINANT-SEVENTH',
      root: 'E1',
    },
    '6FBISXQ0BcPyuvWUnPQxU': {
      id: '6FBISXQ0BcPyuvWUnPQxU',
      name: 'A',
      type: 'MINOR',
      root: 'A1',
    },
    yDkF9XpcbKi17othzHAtU: {
      id: 'yDkF9XpcbKi17othzHAtU',
      name: 'A',
      type: 'MINOR',
      root: 'A1',
    },
    '5cr_VRnxxrUh2fp7JtI0q': {
      id: '5cr_VRnxxrUh2fp7JtI0q',
      name: 'A',
      type: 'MINOR',
      root: 'A1',
    },
    ejSvbgqz4n3cm9stavm9D: {
      id: 'ejSvbgqz4n3cm9stavm9D',
      name: 'A',
      type: 'MINOR',
      root: 'A1',
    },
  },
  progression: {
    id: 'am-blues-V-71I_mwXUn606roHVWrY',
    noteCount: 4,
    tuning: ['G2', 'D2', 'A1', 'E1'],
    name: 'A Minor blues',
    bars: [
      'lh492YRPr1_3-X1W_mJkE',
      'dy-Pe9Kor5sYut2YqZZnq',
      'AVobrClqosfmFICzH4XJb',
      'imT9nu-fnX012riKPlOzU',
      'FsPyvn908XbeiMHZ2dwYW',
      '1JuD0Shgvmcei9a5awVlU',
      'uAJHw6OHhl8KUl-756EEZ',
      'egbLaSaQrp9pz92v7F3yb',
      'NpklWphie8nVyO23_Y6sc',
      'lmqyAakOy2FYpPJ5iUtll',
      'zwcSoX_FKO0RNIot7PWCG',
      'yluFxCrXTEm-YpQDi_qX3',
    ],
  },
}
