import { ProgressionTemplate } from '../types'

export const autumnLeavesTemplate: ProgressionTemplate = {
  progression: {
    id: 'autumn-leaves',
    tuning: ['G2', 'D2', 'A1', 'E1'],
    noteCount: 4,
    name: 'Autumn Leaves',
    bars: [
      'autumn-leaves-bar-0',
      'autumn-leaves-bar-1',
      'autumn-leaves-bar-2',
      'autumn-leaves-bar-3',
      'autumn-leaves-bar-4',
      'autumn-leaves-bar-5',
      'autumn-leaves-bar-6',
      'autumn-leaves-bar-7',
      'autumn-leaves-bar-8',
      'autumn-leaves-bar-9',
      'autumn-leaves-bar-10',
      'autumn-leaves-bar-11',
      'autumn-leaves-bar-12',
      'autumn-leaves-bar-13',
      'autumn-leaves-bar-14',
      'autumn-leaves-bar-15',
      'autumn-leaves-bar-16',
      'autumn-leaves-bar-17',
      'autumn-leaves-bar-18',
      'autumn-leaves-bar-19',
      'autumn-leaves-bar-20',
      'autumn-leaves-bar-21',
      'autumn-leaves-bar-22',
      'autumn-leaves-bar-23',
      'autumn-leaves-bar-24',
      'autumn-leaves-bar-25',
      'autumn-leaves-bar-26',
      'autumn-leaves-bar-27',
      'autumn-leaves-bar-28',
      'autumn-leaves-bar-29',
      'autumn-leaves-bar-30',
      'autumn-leaves-bar-31',
      'autumn-leaves-bar-32',
    ],
  },
  bars: {
    'autumn-leaves-bar-0': {
      id: 'autumn-leaves-bar-0',
      chords: ['autumn-leaves-chord-cm7-0'],
    },
    'autumn-leaves-bar-1': {
      id: 'autumn-leaves-bar-1',
      chords: ['autumn-leaves-chord-f7-1'],
    },
    'autumn-leaves-bar-2': {
      id: 'autumn-leaves-bar-2',
      chords: ['autumn-leaves-chord-bbmaj7-2'],
    },
    'autumn-leaves-bar-3': {
      id: 'autumn-leaves-bar-3',
      chords: ['autumn-leaves-chord-ebmaj7-3'],
    },
    'autumn-leaves-bar-4': {
      id: 'autumn-leaves-bar-4',
      chords: ['autumn-leaves-chord-adim-4'],
    },
    'autumn-leaves-bar-5': {
      id: 'autumn-leaves-bar-5',
      chords: ['autumn-leaves-chord-d7-5'],
    },
    'autumn-leaves-bar-6': {
      id: 'autumn-leaves-bar-6',
      chords: ['autumn-leaves-chord-gm7-6'],
    },
    'autumn-leaves-bar-7': {
      id: 'autumn-leaves-bar-7',
      chords: ['autumn-leaves-chord-gm7-7'],
    },
    'autumn-leaves-bar-8': {
      id: 'autumn-leaves-bar-8',
      chords: ['autumn-leaves-chord-cm7-8'],
    },
    'autumn-leaves-bar-9': {
      id: 'autumn-leaves-bar-9',
      chords: ['autumn-leaves-chord-f7-9'],
    },
    'autumn-leaves-bar-10': {
      id: 'autumn-leaves-bar-10',
      chords: ['autumn-leaves-chord-bbmaj7-10'],
    },
    'autumn-leaves-bar-11': {
      id: 'autumn-leaves-bar-11',
      chords: ['autumn-leaves-chord-ebmaj7-11'],
    },
    'autumn-leaves-bar-12': {
      id: 'autumn-leaves-bar-12',
      chords: ['autumn-leaves-chord-adim-12'],
    },
    'autumn-leaves-bar-13': {
      id: 'autumn-leaves-bar-13',
      chords: ['autumn-leaves-chord-d7-13'],
    },
    'autumn-leaves-bar-14': {
      id: 'autumn-leaves-bar-14',
      chords: ['autumn-leaves-chord-gm7-14'],
    },
    'autumn-leaves-bar-15': {
      id: 'autumn-leaves-bar-15',
      chords: ['autumn-leaves-chord-gm7-15'],
    },
    'autumn-leaves-bar-16': {
      id: 'autumn-leaves-bar-16',
      chords: ['autumn-leaves-chord-adim-16'],
    },
    'autumn-leaves-bar-17': {
      id: 'autumn-leaves-bar-17',
      chords: ['autumn-leaves-chord-d7-17'],
    },
    'autumn-leaves-bar-18': {
      id: 'autumn-leaves-bar-18',
      chords: ['autumn-leaves-chord-gm7-18'],
    },
    'autumn-leaves-bar-19': {
      id: 'autumn-leaves-bar-19',
      chords: ['autumn-leaves-chord-gm7-19'],
    },
    'autumn-leaves-bar-20': {
      id: 'autumn-leaves-bar-20',
      chords: ['autumn-leaves-chord-cm7-20'],
    },
    'autumn-leaves-bar-21': {
      id: 'autumn-leaves-bar-21',
      chords: ['autumn-leaves-chord-f7-21'],
    },
    'autumn-leaves-bar-22': {
      id: 'autumn-leaves-bar-22',
      chords: ['autumn-leaves-chord-bbmaj7-22'],
    },
    'autumn-leaves-bar-23': {
      id: 'autumn-leaves-bar-23',
      chords: ['autumn-leaves-chord-bbmaj7-23'],
    },
    'autumn-leaves-bar-24': {
      id: 'autumn-leaves-bar-24',
      chords: ['autumn-leaves-chord-adim-24'],
    },
    'autumn-leaves-bar-25': {
      id: 'autumn-leaves-bar-25',
      chords: ['autumn-leaves-chord-d7-25'],
    },
    'autumn-leaves-bar-26': {
      id: 'autumn-leaves-bar-26',
      chords: ['autumn-leaves-chord-gm7-26', 'autumn-leaves-chord-gb7-27'],
    },
    'autumn-leaves-bar-27': {
      id: 'autumn-leaves-bar-27',
      chords: ['autumn-leaves-chord-fm7-28', 'autumn-leaves-chord-e7-29'],
    },
    'autumn-leaves-bar-28': {
      id: 'autumn-leaves-bar-28',
      chords: ['autumn-leaves-chord-ebmaj7-30'],
    },
    'autumn-leaves-bar-29': {
      id: 'autumn-leaves-bar-29',
      chords: ['autumn-leaves-chord-d7-31'],
    },
    'autumn-leaves-bar-30': {
      id: 'autumn-leaves-bar-30',
      chords: ['autumn-leaves-chord-gm7-32'],
    },
    'autumn-leaves-bar-31': {
      id: 'autumn-leaves-bar-31',
      chords: ['autumn-leaves-chord-gm7-33'],
    },
    'autumn-leaves-bar-32': {
      id: 'autumn-leaves-bar-32',
      chords: ['autumn-leaves-chord-cm7-34'],
    },
  },
  chords: {
    'autumn-leaves-chord-cm7-0': {
      id: 'autumn-leaves-chord-cm7-0',
      name: 'C',
      type: 'MINOR-SEVENTH',
      root: 'C2',
    },
    'autumn-leaves-chord-f7-1': {
      id: 'autumn-leaves-chord-f7-1',
      name: 'F',
      type: 'DOMINANT-SEVENTH',
      root: 'F1',
    },
    'autumn-leaves-chord-bbmaj7-2': {
      id: 'autumn-leaves-chord-bbmaj7-2',
      name: 'Bb',
      type: 'MAJOR-SEVENTH',
      root: 'Bb1',
    },
    'autumn-leaves-chord-ebmaj7-3': {
      id: 'autumn-leaves-chord-ebmaj7-3',
      name: 'Eb',
      type: 'MAJOR-SEVENTH',
      root: 'Eb2',
    },
    'autumn-leaves-chord-adim-4': {
      id: 'autumn-leaves-chord-adim-4',
      name: 'A',
      type: 'DIMINISHED',
      root: 'A1',
    },
    'autumn-leaves-chord-d7-5': {
      id: 'autumn-leaves-chord-d7-5',
      name: 'D',
      type: 'DOMINANT-SEVENTH',
      root: 'D2',
    },
    'autumn-leaves-chord-gm7-6': {
      id: 'autumn-leaves-chord-gm7-6',
      name: 'G',
      type: 'MINOR-SEVENTH',
      root: 'G1',
    },
    'autumn-leaves-chord-gm7-7': {
      id: 'autumn-leaves-chord-gm7-7',
      name: 'G',
      type: 'MINOR-SEVENTH',
      root: 'G1',
    },
    'autumn-leaves-chord-cm7-8': {
      id: 'autumn-leaves-chord-cm7-8',
      name: 'C',
      type: 'MINOR-SEVENTH',
      root: 'C2',
    },
    'autumn-leaves-chord-f7-9': {
      id: 'autumn-leaves-chord-f7-9',
      name: 'F',
      type: 'DOMINANT-SEVENTH',
      root: 'F1',
    },
    'autumn-leaves-chord-bbmaj7-10': {
      id: 'autumn-leaves-chord-bbmaj7-10',
      name: 'Bb',
      type: 'MAJOR-SEVENTH',
      root: 'Bb1',
    },
    'autumn-leaves-chord-ebmaj7-11': {
      id: 'autumn-leaves-chord-ebmaj7-11',
      name: 'Eb',
      type: 'MAJOR-SEVENTH',
      root: 'Eb2',
    },
    'autumn-leaves-chord-adim-12': {
      id: 'autumn-leaves-chord-adim-12',
      name: 'A',
      type: 'DIMINISHED',
      root: 'A1',
    },
    'autumn-leaves-chord-d7-13': {
      id: 'autumn-leaves-chord-d7-13',
      name: 'D',
      type: 'DOMINANT-SEVENTH',
      root: 'D2',
    },
    'autumn-leaves-chord-gm7-14': {
      id: 'autumn-leaves-chord-gm7-14',
      name: 'G',
      type: 'MINOR-SEVENTH',
      root: 'G1',
    },
    'autumn-leaves-chord-gm7-15': {
      id: 'autumn-leaves-chord-gm7-15',
      name: 'G',
      type: 'MINOR-SEVENTH',
      root: 'G1',
    },
    'autumn-leaves-chord-adim-16': {
      id: 'autumn-leaves-chord-adim-16',
      name: 'A',
      type: 'DIMINISHED',
      root: 'A1',
    },
    'autumn-leaves-chord-d7-17': {
      id: 'autumn-leaves-chord-d7-17',
      name: 'D',
      type: 'DOMINANT-SEVENTH',
      root: 'D2',
    },
    'autumn-leaves-chord-gm7-18': {
      id: 'autumn-leaves-chord-gm7-18',
      name: 'G',
      type: 'MINOR-SEVENTH',
      root: 'G1',
    },
    'autumn-leaves-chord-gm7-19': {
      id: 'autumn-leaves-chord-gm7-19',
      name: 'G',
      type: 'MINOR-SEVENTH',
      root: 'G1',
    },
    'autumn-leaves-chord-cm7-20': {
      id: 'autumn-leaves-chord-cm7-20',
      name: 'C',
      type: 'MINOR-SEVENTH',
      root: 'C2',
    },
    'autumn-leaves-chord-f7-21': {
      id: 'autumn-leaves-chord-f7-21',
      name: 'F',
      type: 'DOMINANT-SEVENTH',
      root: 'F1',
    },
    'autumn-leaves-chord-bbmaj7-22': {
      id: 'autumn-leaves-chord-bbmaj7-22',
      name: 'Bb',
      type: 'MAJOR-SEVENTH',
      root: 'Bb1',
    },
    'autumn-leaves-chord-bbmaj7-23': {
      id: 'autumn-leaves-chord-bbmaj7-23',
      name: 'Bb',
      type: 'MAJOR-SEVENTH',
      root: 'Bb1',
    },
    'autumn-leaves-chord-adim-24': {
      id: 'autumn-leaves-chord-adim-24',
      name: 'A',
      type: 'DIMINISHED',
      root: 'A1',
      tags: [],
    },
    'autumn-leaves-chord-d7-25': {
      id: 'autumn-leaves-chord-d7-25',
      name: 'D',
      type: 'DOMINANT-SEVENTH',
      root: 'D2',
      tags: [],
    },
    'autumn-leaves-chord-gm7-26': {
      id: 'autumn-leaves-chord-gm7-26',
      name: 'G',
      type: 'MINOR-SEVENTH',
      root: 'G1',
      noteCount: 2,
    },
    'autumn-leaves-chord-gb7-27': {
      id: 'autumn-leaves-chord-gb7-27',
      name: 'Gb',
      type: 'DOMINANT-SEVENTH',
      root: 'Gb1',
      noteCount: 2,
    },
    'autumn-leaves-chord-fm7-28': {
      id: 'autumn-leaves-chord-fm7-28',
      name: 'F',
      type: 'MINOR-SEVENTH',
      root: 'F1',
      noteCount: 2,
    },
    'autumn-leaves-chord-e7-29': {
      id: 'autumn-leaves-chord-e7-29',
      name: 'E',
      type: 'DOMINANT-SEVENTH',
      root: 'E1',
      noteCount: 2,
    },
    'autumn-leaves-chord-ebmaj7-30': {
      id: 'autumn-leaves-chord-ebmaj7-30',
      name: 'Eb',
      type: 'MAJOR-SEVENTH',
      root: 'Eb2',
    },
    'autumn-leaves-chord-d7-31': {
      id: 'autumn-leaves-chord-d7-31',
      name: 'D',
      type: 'DOMINANT-SEVENTH',
      root: 'D2',
    },
    'autumn-leaves-chord-gm7-32': {
      id: 'autumn-leaves-chord-gm7-32',
      name: 'G',
      type: 'MINOR-SEVENTH',
      root: 'G1',
    },
    'autumn-leaves-chord-gm7-33': {
      id: 'autumn-leaves-chord-gm7-33',
      name: 'G',
      type: 'MINOR-SEVENTH',
      root: 'G1',
    },
    'autumn-leaves-chord-cm7-34': {
      id: 'autumn-leaves-chord-cm7-34',
      name: 'C',
      type: 'MINOR-SEVENTH',
      root: 'C2',
    },
  },
}
